services:
  - type: web
    name: ticket-tracker
    runtime: node
    healthCheckPath: /api/health
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_DIR
        value: /tmp/data
      - key: SESSION_DURATION_HOURS
        value: "12"
      - key: TICKET_APP_DEFAULT_PASSWORD
        value: Qwer1234..
      - key: SEED_FORCE_RESET
        value: "false"
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        value: 34.159.196.244
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASS
        value: tweakDenseicky%0
      - key: JWT_SECRET
        value: 2fd84125f36d0e74653be1fc65e0de0
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
